version: "3"

services:
  redis:
    container_name: popselen-redis
    image: redis:7.0.0
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redisdata:/data

volumes:
  redisdata:
